DROP TABLE IF EXISTS volunteer;

CREATE TABLE volunteer (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL
);
